class RegistryError(Exception):
    """Base exception for all registry-related errors."""
    pass

class ModelNotFoundError(RegistryError):
    """Raised when a requested model is not found."""
    pass

class RegistryNotLoadedError(RegistryError):
    """Raised when trying to access registry before loading data."""
    pass

class RegistryLoadError(Exception):
    """Base exception for registry loading errors."""
    pass

class CompiledSqlMissingError(RuntimeError):
    """Raised when compiled SQL cannot be found in the manifest.

    This typically happens when the manifest was generated by ``dbt parse``
    (e.g., via the dbt Language Server) instead of ``dbt compile`` or
    ``dbt run``.  Those commands embed ``compiled_code`` directly in each
    manifest node; ``dbt parse`` does not.

    Resolution options
    ------------------
    1. Run ``dbt compile`` in your project and re-invoke with
       ``compiled_sql_source="manifest"`` (the default).  This is the
       safest option — compiled SQL is always in sync with your models.

    2. Pass ``compiled_sql_source="target_dir"`` to fall back to any
       previously compiled ``.sql`` files under ``target/compiled/``.
       These files may be **stale** if models have changed since the last
       ``dbt compile`` run.

    3. Pass ``compiled_sql_source="auto_compile"`` together with
       ``project_dir`` to let dbt-column-lineage run ``dbt compile``
       automatically before resolving lineage.
    """
